### ISSUE TITLE
Make a desktop version

### ISSUE THREAD

**Issue by ghost** [arcticsn0w/Minimal-Hosts-Blocker#1]
Take, for example, [google.com](https://www.google.com/) on a Windows PC:

![img](https://cloud.githubusercontent.com/assets/9056756/10825984/dd5b8f94-7e3d-11e5-9520-28a933b8f0fd.png)

Look at all those ads! :cry:

**Comment by arcetera** [comment]
we're not making a desktop version as there are other, better adblockers for desktops
